package jp.co.fnj.storage.entity.model.generat;

import java.util.Date;

public class TBookmark {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bookmark.BOOKMARK_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private Integer bookmarkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bookmark.USER_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bookmark.FILE_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private Integer fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bookmark.FOLDER_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private Integer folderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bookmark.CREATE_USER
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bookmark.CREATE_DATE
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bookmark.UPDATE_USER
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bookmark.UPDATE_DATE
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bookmark.BOOKMARK_ID
     *
     * @return the value of t_bookmark.BOOKMARK_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public Integer getBookmarkId() {
        return bookmarkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bookmark.BOOKMARK_ID
     *
     * @param bookmarkId the value for t_bookmark.BOOKMARK_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setBookmarkId(Integer bookmarkId) {
        this.bookmarkId = bookmarkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bookmark.USER_ID
     *
     * @return the value of t_bookmark.USER_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bookmark.USER_ID
     *
     * @param userId the value for t_bookmark.USER_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bookmark.FILE_ID
     *
     * @return the value of t_bookmark.FILE_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bookmark.FILE_ID
     *
     * @param fileId the value for t_bookmark.FILE_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bookmark.FOLDER_ID
     *
     * @return the value of t_bookmark.FOLDER_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public Integer getFolderId() {
        return folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bookmark.FOLDER_ID
     *
     * @param folderId the value for t_bookmark.FOLDER_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setFolderId(Integer folderId) {
        this.folderId = folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bookmark.CREATE_USER
     *
     * @return the value of t_bookmark.CREATE_USER
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bookmark.CREATE_USER
     *
     * @param createUser the value for t_bookmark.CREATE_USER
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bookmark.CREATE_DATE
     *
     * @return the value of t_bookmark.CREATE_DATE
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bookmark.CREATE_DATE
     *
     * @param createDate the value for t_bookmark.CREATE_DATE
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bookmark.UPDATE_USER
     *
     * @return the value of t_bookmark.UPDATE_USER
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bookmark.UPDATE_USER
     *
     * @param updateUser the value for t_bookmark.UPDATE_USER
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bookmark.UPDATE_DATE
     *
     * @return the value of t_bookmark.UPDATE_DATE
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bookmark.UPDATE_DATE
     *
     * @param updateDate the value for t_bookmark.UPDATE_DATE
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}