package jp.co.fnj.storage.entity.model.generat;

import java.util.Date;

public class TExternalServiceObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_external_service_object.FILE_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private String fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_external_service_object.FILE_PATH
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_external_service_object.CREATE_USER
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_external_service_object.CREATE_DATE
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_external_service_object.UPDATE_USER
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_external_service_object.UPDATE_DATE
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_external_service_object.FILE_ID
     *
     * @return the value of t_external_service_object.FILE_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_external_service_object.FILE_ID
     *
     * @param fileId the value for t_external_service_object.FILE_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_external_service_object.FILE_PATH
     *
     * @return the value of t_external_service_object.FILE_PATH
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_external_service_object.FILE_PATH
     *
     * @param filePath the value for t_external_service_object.FILE_PATH
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_external_service_object.CREATE_USER
     *
     * @return the value of t_external_service_object.CREATE_USER
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_external_service_object.CREATE_USER
     *
     * @param createUser the value for t_external_service_object.CREATE_USER
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_external_service_object.CREATE_DATE
     *
     * @return the value of t_external_service_object.CREATE_DATE
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_external_service_object.CREATE_DATE
     *
     * @param createDate the value for t_external_service_object.CREATE_DATE
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_external_service_object.UPDATE_USER
     *
     * @return the value of t_external_service_object.UPDATE_USER
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_external_service_object.UPDATE_USER
     *
     * @param updateUser the value for t_external_service_object.UPDATE_USER
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_external_service_object.UPDATE_DATE
     *
     * @return the value of t_external_service_object.UPDATE_DATE
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_external_service_object.UPDATE_DATE
     *
     * @param updateDate the value for t_external_service_object.UPDATE_DATE
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}