package jp.co.fnj.storage.entity.model.generat;

import java.util.Date;

public class TFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.FILE_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private String fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.FOLDER_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private String folderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.FILE_NAME
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.S3_FILE_NAME
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private String s3FileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.DELETE_FLG
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private Boolean deleteFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.S3_OBJECT_KEY
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private String s3ObjectKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.FILE_SIZE
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private Long fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.CREATE_USER
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.CREATE_DATE
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.UPDATE_USER
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.UPDATE_DATE
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.FILE_ID
     *
     * @return the value of t_file.FILE_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.FILE_ID
     *
     * @param fileId the value for t_file.FILE_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.FOLDER_ID
     *
     * @return the value of t_file.FOLDER_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public String getFolderId() {
        return folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.FOLDER_ID
     *
     * @param folderId the value for t_file.FOLDER_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setFolderId(String folderId) {
        this.folderId = folderId == null ? null : folderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.FILE_NAME
     *
     * @return the value of t_file.FILE_NAME
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.FILE_NAME
     *
     * @param fileName the value for t_file.FILE_NAME
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.S3_FILE_NAME
     *
     * @return the value of t_file.S3_FILE_NAME
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public String getS3FileName() {
        return s3FileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.S3_FILE_NAME
     *
     * @param s3FileName the value for t_file.S3_FILE_NAME
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setS3FileName(String s3FileName) {
        this.s3FileName = s3FileName == null ? null : s3FileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.DELETE_FLG
     *
     * @return the value of t_file.DELETE_FLG
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public Boolean getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.DELETE_FLG
     *
     * @param deleteFlg the value for t_file.DELETE_FLG
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setDeleteFlg(Boolean deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.S3_OBJECT_KEY
     *
     * @return the value of t_file.S3_OBJECT_KEY
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public String getS3ObjectKey() {
        return s3ObjectKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.S3_OBJECT_KEY
     *
     * @param s3ObjectKey the value for t_file.S3_OBJECT_KEY
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setS3ObjectKey(String s3ObjectKey) {
        this.s3ObjectKey = s3ObjectKey == null ? null : s3ObjectKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.FILE_SIZE
     *
     * @return the value of t_file.FILE_SIZE
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.FILE_SIZE
     *
     * @param fileSize the value for t_file.FILE_SIZE
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.CREATE_USER
     *
     * @return the value of t_file.CREATE_USER
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.CREATE_USER
     *
     * @param createUser the value for t_file.CREATE_USER
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.CREATE_DATE
     *
     * @return the value of t_file.CREATE_DATE
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.CREATE_DATE
     *
     * @param createDate the value for t_file.CREATE_DATE
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.UPDATE_USER
     *
     * @return the value of t_file.UPDATE_USER
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.UPDATE_USER
     *
     * @param updateUser the value for t_file.UPDATE_USER
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.UPDATE_DATE
     *
     * @return the value of t_file.UPDATE_DATE
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.UPDATE_DATE
     *
     * @param updateDate the value for t_file.UPDATE_DATE
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}