package jp.co.fnj.storage.entity.model.generat;

public class TFullTextSearch extends TFullTextSearchKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_full_text_search.TEXT_DATA
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private String textData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_full_text_search.TEXT_DATA
     *
     * @return the value of t_full_text_search.TEXT_DATA
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public String getTextData() {
        return textData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_full_text_search.TEXT_DATA
     *
     * @param textData the value for t_full_text_search.TEXT_DATA
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setTextData(String textData) {
        this.textData = textData == null ? null : textData.trim();
    }
}