package jp.co.fnj.storage.entity.model.generat;

public class TFullTextSearchKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_full_text_search.FILE_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private String fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_full_text_search.FILE_NO
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private Integer fileNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_full_text_search.FILE_ID
     *
     * @return the value of t_full_text_search.FILE_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_full_text_search.FILE_ID
     *
     * @param fileId the value for t_full_text_search.FILE_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_full_text_search.FILE_NO
     *
     * @return the value of t_full_text_search.FILE_NO
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public Integer getFileNo() {
        return fileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_full_text_search.FILE_NO
     *
     * @param fileNo the value for t_full_text_search.FILE_NO
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setFileNo(Integer fileNo) {
        this.fileNo = fileNo;
    }
}