package jp.co.fnj.storage.entity.model.generat;

import java.util.Date;

public class TSortOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sort_order.SORT_ORDER_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private Integer sortOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sort_order.PARENT_FOLDER_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private String parentFolderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sort_order.FILE_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private String fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sort_order.FOLDER_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private String folderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sort_order.SORT_ORDER
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private Integer sortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sort_order.CREATE_USER
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sort_order.CREATE_DATE
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sort_order.UPDATE_USER
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sort_order.UPDATE_DATE
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sort_order.SORT_ORDER_ID
     *
     * @return the value of t_sort_order.SORT_ORDER_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public Integer getSortOrderId() {
        return sortOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sort_order.SORT_ORDER_ID
     *
     * @param sortOrderId the value for t_sort_order.SORT_ORDER_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setSortOrderId(Integer sortOrderId) {
        this.sortOrderId = sortOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sort_order.PARENT_FOLDER_ID
     *
     * @return the value of t_sort_order.PARENT_FOLDER_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public String getParentFolderId() {
        return parentFolderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sort_order.PARENT_FOLDER_ID
     *
     * @param parentFolderId the value for t_sort_order.PARENT_FOLDER_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setParentFolderId(String parentFolderId) {
        this.parentFolderId = parentFolderId == null ? null : parentFolderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sort_order.FILE_ID
     *
     * @return the value of t_sort_order.FILE_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sort_order.FILE_ID
     *
     * @param fileId the value for t_sort_order.FILE_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sort_order.FOLDER_ID
     *
     * @return the value of t_sort_order.FOLDER_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public String getFolderId() {
        return folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sort_order.FOLDER_ID
     *
     * @param folderId the value for t_sort_order.FOLDER_ID
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setFolderId(String folderId) {
        this.folderId = folderId == null ? null : folderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sort_order.SORT_ORDER
     *
     * @return the value of t_sort_order.SORT_ORDER
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sort_order.SORT_ORDER
     *
     * @param sortOrder the value for t_sort_order.SORT_ORDER
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sort_order.CREATE_USER
     *
     * @return the value of t_sort_order.CREATE_USER
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sort_order.CREATE_USER
     *
     * @param createUser the value for t_sort_order.CREATE_USER
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sort_order.CREATE_DATE
     *
     * @return the value of t_sort_order.CREATE_DATE
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sort_order.CREATE_DATE
     *
     * @param createDate the value for t_sort_order.CREATE_DATE
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sort_order.UPDATE_USER
     *
     * @return the value of t_sort_order.UPDATE_USER
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sort_order.UPDATE_USER
     *
     * @param updateUser the value for t_sort_order.UPDATE_USER
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sort_order.UPDATE_DATE
     *
     * @return the value of t_sort_order.UPDATE_DATE
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sort_order.UPDATE_DATE
     *
     * @param updateDate the value for t_sort_order.UPDATE_DATE
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}