package jp.co.fnj.storage.api.entity.model.generat;

import java.time.LocalDateTime;

public class TBookmark {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_BOOKMARK.BOOKMARK_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private Integer bookmarkId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_BOOKMARK.USER_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_BOOKMARK.FILE_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private Integer fileId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_BOOKMARK.FOLDER_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private Integer folderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_BOOKMARK.CREATE_USER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_BOOKMARK.CREATE_DATE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private LocalDateTime createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_BOOKMARK.UPDATE_USER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private String updateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_BOOKMARK.UPDATE_DATE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private LocalDateTime updateDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_BOOKMARK.BOOKMARK_ID
	 * @return  the value of T_BOOKMARK.BOOKMARK_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public Integer getBookmarkId() {
		return bookmarkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_BOOKMARK.BOOKMARK_ID
	 * @param bookmarkId  the value for T_BOOKMARK.BOOKMARK_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setBookmarkId(Integer bookmarkId) {
		this.bookmarkId = bookmarkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_BOOKMARK.USER_ID
	 * @return  the value of T_BOOKMARK.USER_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_BOOKMARK.USER_ID
	 * @param userId  the value for T_BOOKMARK.USER_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_BOOKMARK.FILE_ID
	 * @return  the value of T_BOOKMARK.FILE_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public Integer getFileId() {
		return fileId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_BOOKMARK.FILE_ID
	 * @param fileId  the value for T_BOOKMARK.FILE_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setFileId(Integer fileId) {
		this.fileId = fileId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_BOOKMARK.FOLDER_ID
	 * @return  the value of T_BOOKMARK.FOLDER_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public Integer getFolderId() {
		return folderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_BOOKMARK.FOLDER_ID
	 * @param folderId  the value for T_BOOKMARK.FOLDER_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setFolderId(Integer folderId) {
		this.folderId = folderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_BOOKMARK.CREATE_USER
	 * @return  the value of T_BOOKMARK.CREATE_USER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_BOOKMARK.CREATE_USER
	 * @param createUser  the value for T_BOOKMARK.CREATE_USER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser == null ? null : createUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_BOOKMARK.CREATE_DATE
	 * @return  the value of T_BOOKMARK.CREATE_DATE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public LocalDateTime getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_BOOKMARK.CREATE_DATE
	 * @param createDate  the value for T_BOOKMARK.CREATE_DATE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setCreateDate(LocalDateTime createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_BOOKMARK.UPDATE_USER
	 * @return  the value of T_BOOKMARK.UPDATE_USER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_BOOKMARK.UPDATE_USER
	 * @param updateUser  the value for T_BOOKMARK.UPDATE_USER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser == null ? null : updateUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_BOOKMARK.UPDATE_DATE
	 * @return  the value of T_BOOKMARK.UPDATE_DATE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public LocalDateTime getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_BOOKMARK.UPDATE_DATE
	 * @param updateDate  the value for T_BOOKMARK.UPDATE_DATE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setUpdateDate(LocalDateTime updateDate) {
		this.updateDate = updateDate;
	}
}