package jp.co.fnj.storage.api.entity.model.generat;

import java.time.LocalDateTime;

public class TExternalServiceObject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_EXTERNAL_SERVICE_OBJECT.FILE_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private String fileId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_EXTERNAL_SERVICE_OBJECT.FILE_PATH
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private String filePath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_EXTERNAL_SERVICE_OBJECT.CREATE_USER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_EXTERNAL_SERVICE_OBJECT.CREATE_DATE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private LocalDateTime createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_EXTERNAL_SERVICE_OBJECT.UPDATE_USER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private String updateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_EXTERNAL_SERVICE_OBJECT.UPDATE_DATE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private LocalDateTime updateDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_EXTERNAL_SERVICE_OBJECT.FILE_ID
	 * @return  the value of T_EXTERNAL_SERVICE_OBJECT.FILE_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public String getFileId() {
		return fileId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_EXTERNAL_SERVICE_OBJECT.FILE_ID
	 * @param fileId  the value for T_EXTERNAL_SERVICE_OBJECT.FILE_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setFileId(String fileId) {
		this.fileId = fileId == null ? null : fileId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_EXTERNAL_SERVICE_OBJECT.FILE_PATH
	 * @return  the value of T_EXTERNAL_SERVICE_OBJECT.FILE_PATH
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public String getFilePath() {
		return filePath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_EXTERNAL_SERVICE_OBJECT.FILE_PATH
	 * @param filePath  the value for T_EXTERNAL_SERVICE_OBJECT.FILE_PATH
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setFilePath(String filePath) {
		this.filePath = filePath == null ? null : filePath.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_EXTERNAL_SERVICE_OBJECT.CREATE_USER
	 * @return  the value of T_EXTERNAL_SERVICE_OBJECT.CREATE_USER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_EXTERNAL_SERVICE_OBJECT.CREATE_USER
	 * @param createUser  the value for T_EXTERNAL_SERVICE_OBJECT.CREATE_USER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser == null ? null : createUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_EXTERNAL_SERVICE_OBJECT.CREATE_DATE
	 * @return  the value of T_EXTERNAL_SERVICE_OBJECT.CREATE_DATE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public LocalDateTime getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_EXTERNAL_SERVICE_OBJECT.CREATE_DATE
	 * @param createDate  the value for T_EXTERNAL_SERVICE_OBJECT.CREATE_DATE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setCreateDate(LocalDateTime createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_EXTERNAL_SERVICE_OBJECT.UPDATE_USER
	 * @return  the value of T_EXTERNAL_SERVICE_OBJECT.UPDATE_USER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_EXTERNAL_SERVICE_OBJECT.UPDATE_USER
	 * @param updateUser  the value for T_EXTERNAL_SERVICE_OBJECT.UPDATE_USER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser == null ? null : updateUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_EXTERNAL_SERVICE_OBJECT.UPDATE_DATE
	 * @return  the value of T_EXTERNAL_SERVICE_OBJECT.UPDATE_DATE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public LocalDateTime getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_EXTERNAL_SERVICE_OBJECT.UPDATE_DATE
	 * @param updateDate  the value for T_EXTERNAL_SERVICE_OBJECT.UPDATE_DATE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setUpdateDate(LocalDateTime updateDate) {
		this.updateDate = updateDate;
	}
}