package jp.co.fnj.storage.api.entity.model.generat;

import java.time.LocalDateTime;

public class TFile {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_FILE.FILE_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private String fileId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_FILE.FOLDER_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private String folderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_FILE.FILE_NAME
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private String fileName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_FILE.S3_FILE_NAME
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private String s3FileName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_FILE.DELETE_FLG
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private Boolean deleteFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_FILE.S3_OBJECT_KEY
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private String s3ObjectKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_FILE.FILE_SIZE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private Long fileSize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_FILE.CREATE_USER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_FILE.CREATE_DATE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private LocalDateTime createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_FILE.UPDATE_USER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private String updateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_FILE.UPDATE_DATE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private LocalDateTime updateDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_FILE.FILE_ID
	 * @return  the value of T_FILE.FILE_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public String getFileId() {
		return fileId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_FILE.FILE_ID
	 * @param fileId  the value for T_FILE.FILE_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setFileId(String fileId) {
		this.fileId = fileId == null ? null : fileId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_FILE.FOLDER_ID
	 * @return  the value of T_FILE.FOLDER_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public String getFolderId() {
		return folderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_FILE.FOLDER_ID
	 * @param folderId  the value for T_FILE.FOLDER_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setFolderId(String folderId) {
		this.folderId = folderId == null ? null : folderId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_FILE.FILE_NAME
	 * @return  the value of T_FILE.FILE_NAME
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public String getFileName() {
		return fileName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_FILE.FILE_NAME
	 * @param fileName  the value for T_FILE.FILE_NAME
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setFileName(String fileName) {
		this.fileName = fileName == null ? null : fileName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_FILE.S3_FILE_NAME
	 * @return  the value of T_FILE.S3_FILE_NAME
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public String getS3FileName() {
		return s3FileName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_FILE.S3_FILE_NAME
	 * @param s3FileName  the value for T_FILE.S3_FILE_NAME
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setS3FileName(String s3FileName) {
		this.s3FileName = s3FileName == null ? null : s3FileName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_FILE.DELETE_FLG
	 * @return  the value of T_FILE.DELETE_FLG
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public Boolean getDeleteFlg() {
		return deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_FILE.DELETE_FLG
	 * @param deleteFlg  the value for T_FILE.DELETE_FLG
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setDeleteFlg(Boolean deleteFlg) {
		this.deleteFlg = deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_FILE.S3_OBJECT_KEY
	 * @return  the value of T_FILE.S3_OBJECT_KEY
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public String getS3ObjectKey() {
		return s3ObjectKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_FILE.S3_OBJECT_KEY
	 * @param s3ObjectKey  the value for T_FILE.S3_OBJECT_KEY
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setS3ObjectKey(String s3ObjectKey) {
		this.s3ObjectKey = s3ObjectKey == null ? null : s3ObjectKey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_FILE.FILE_SIZE
	 * @return  the value of T_FILE.FILE_SIZE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public Long getFileSize() {
		return fileSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_FILE.FILE_SIZE
	 * @param fileSize  the value for T_FILE.FILE_SIZE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setFileSize(Long fileSize) {
		this.fileSize = fileSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_FILE.CREATE_USER
	 * @return  the value of T_FILE.CREATE_USER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_FILE.CREATE_USER
	 * @param createUser  the value for T_FILE.CREATE_USER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser == null ? null : createUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_FILE.CREATE_DATE
	 * @return  the value of T_FILE.CREATE_DATE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public LocalDateTime getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_FILE.CREATE_DATE
	 * @param createDate  the value for T_FILE.CREATE_DATE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setCreateDate(LocalDateTime createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_FILE.UPDATE_USER
	 * @return  the value of T_FILE.UPDATE_USER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_FILE.UPDATE_USER
	 * @param updateUser  the value for T_FILE.UPDATE_USER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser == null ? null : updateUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_FILE.UPDATE_DATE
	 * @return  the value of T_FILE.UPDATE_DATE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public LocalDateTime getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_FILE.UPDATE_DATE
	 * @param updateDate  the value for T_FILE.UPDATE_DATE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setUpdateDate(LocalDateTime updateDate) {
		this.updateDate = updateDate;
	}
}