package jp.co.fnj.storage.api.entity.model.generat;

import java.io.Serializable;
import java.time.LocalDateTime;

public class TFolder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_folder.FOLDER_ID
     *
     * @mbg.generated
     */
    private String folderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_folder.PARENT_FOLDER_ID
     *
     * @mbg.generated
     */
    private String parentFolderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_folder.FOLDER_GROUP
     *
     * @mbg.generated
     */
    private Integer folderGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_folder.FOLDER_NAME
     *
     * @mbg.generated
     */
    private String folderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_folder.S3_FOLDER_NAME
     *
     * @mbg.generated
     */
    private String s3FolderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_folder.DEVELOPER_ID
     *
     * @mbg.generated
     */
    private String developerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_folder.MANSION_ID
     *
     * @mbg.generated
     */
    private String mansionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_folder.S3_OBJECT_KEY
     *
     * @mbg.generated
     */
    private String s3ObjectKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_folder.DELETE_FLG
     *
     * @mbg.generated
     */
    private Boolean deleteFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_folder.PRIVATE_FLG
     *
     * @mbg.generated
     */
    private Boolean privateFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_folder.EXPLANATORY_TEXT
     *
     * @mbg.generated
     */
    private String explanatoryText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_folder.CREATE_USER
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_folder.CREATE_DATE
     *
     * @mbg.generated
     */
    private LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_folder.UPDATE_USER
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_folder.UPDATE_DATE
     *
     * @mbg.generated
     */
    private LocalDateTime updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_folder.FOLDER_ID
     *
     * @return the value of t_folder.FOLDER_ID
     *
     * @mbg.generated
     */
    public String getFolderId() {
        return folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_folder.FOLDER_ID
     *
     * @param folderId the value for t_folder.FOLDER_ID
     *
     * @mbg.generated
     */
    public void setFolderId(String folderId) {
        this.folderId = folderId == null ? null : folderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_folder.PARENT_FOLDER_ID
     *
     * @return the value of t_folder.PARENT_FOLDER_ID
     *
     * @mbg.generated
     */
    public String getParentFolderId() {
        return parentFolderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_folder.PARENT_FOLDER_ID
     *
     * @param parentFolderId the value for t_folder.PARENT_FOLDER_ID
     *
     * @mbg.generated
     */
    public void setParentFolderId(String parentFolderId) {
        this.parentFolderId = parentFolderId == null ? null : parentFolderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_folder.FOLDER_GROUP
     *
     * @return the value of t_folder.FOLDER_GROUP
     *
     * @mbg.generated
     */
    public Integer getFolderGroup() {
        return folderGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_folder.FOLDER_GROUP
     *
     * @param folderGroup the value for t_folder.FOLDER_GROUP
     *
     * @mbg.generated
     */
    public void setFolderGroup(Integer folderGroup) {
        this.folderGroup = folderGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_folder.FOLDER_NAME
     *
     * @return the value of t_folder.FOLDER_NAME
     *
     * @mbg.generated
     */
    public String getFolderName() {
        return folderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_folder.FOLDER_NAME
     *
     * @param folderName the value for t_folder.FOLDER_NAME
     *
     * @mbg.generated
     */
    public void setFolderName(String folderName) {
        this.folderName = folderName == null ? null : folderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_folder.S3_FOLDER_NAME
     *
     * @return the value of t_folder.S3_FOLDER_NAME
     *
     * @mbg.generated
     */
    public String getS3FolderName() {
        return s3FolderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_folder.S3_FOLDER_NAME
     *
     * @param s3FolderName the value for t_folder.S3_FOLDER_NAME
     *
     * @mbg.generated
     */
    public void setS3FolderName(String s3FolderName) {
        this.s3FolderName = s3FolderName == null ? null : s3FolderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_folder.DEVELOPER_ID
     *
     * @return the value of t_folder.DEVELOPER_ID
     *
     * @mbg.generated
     */
    public String getDeveloperId() {
        return developerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_folder.DEVELOPER_ID
     *
     * @param developerId the value for t_folder.DEVELOPER_ID
     *
     * @mbg.generated
     */
    public void setDeveloperId(String developerId) {
        this.developerId = developerId == null ? null : developerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_folder.MANSION_ID
     *
     * @return the value of t_folder.MANSION_ID
     *
     * @mbg.generated
     */
    public String getMansionId() {
        return mansionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_folder.MANSION_ID
     *
     * @param mansionId the value for t_folder.MANSION_ID
     *
     * @mbg.generated
     */
    public void setMansionId(String mansionId) {
        this.mansionId = mansionId == null ? null : mansionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_folder.S3_OBJECT_KEY
     *
     * @return the value of t_folder.S3_OBJECT_KEY
     *
     * @mbg.generated
     */
    public String getS3ObjectKey() {
        return s3ObjectKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_folder.S3_OBJECT_KEY
     *
     * @param s3ObjectKey the value for t_folder.S3_OBJECT_KEY
     *
     * @mbg.generated
     */
    public void setS3ObjectKey(String s3ObjectKey) {
        this.s3ObjectKey = s3ObjectKey == null ? null : s3ObjectKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_folder.DELETE_FLG
     *
     * @return the value of t_folder.DELETE_FLG
     *
     * @mbg.generated
     */
    public Boolean getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_folder.DELETE_FLG
     *
     * @param deleteFlg the value for t_folder.DELETE_FLG
     *
     * @mbg.generated
     */
    public void setDeleteFlg(Boolean deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_folder.PRIVATE_FLG
     *
     * @return the value of t_folder.PRIVATE_FLG
     *
     * @mbg.generated
     */
    public Boolean getPrivateFlg() {
        return privateFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_folder.PRIVATE_FLG
     *
     * @param privateFlg the value for t_folder.PRIVATE_FLG
     *
     * @mbg.generated
     */
    public void setPrivateFlg(Boolean privateFlg) {
        this.privateFlg = privateFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_folder.EXPLANATORY_TEXT
     *
     * @return the value of t_folder.EXPLANATORY_TEXT
     *
     * @mbg.generated
     */
    public String getExplanatoryText() {
        return explanatoryText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_folder.EXPLANATORY_TEXT
     *
     * @param explanatoryText the value for t_folder.EXPLANATORY_TEXT
     *
     * @mbg.generated
     */
    public void setExplanatoryText(String explanatoryText) {
        this.explanatoryText = explanatoryText == null ? null : explanatoryText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_folder.CREATE_USER
     *
     * @return the value of t_folder.CREATE_USER
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_folder.CREATE_USER
     *
     * @param createUser the value for t_folder.CREATE_USER
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_folder.CREATE_DATE
     *
     * @return the value of t_folder.CREATE_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_folder.CREATE_DATE
     *
     * @param createDate the value for t_folder.CREATE_DATE
     *
     * @mbg.generated
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_folder.UPDATE_USER
     *
     * @return the value of t_folder.UPDATE_USER
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_folder.UPDATE_USER
     *
     * @param updateUser the value for t_folder.UPDATE_USER
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_folder.UPDATE_DATE
     *
     * @return the value of t_folder.UPDATE_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_folder.UPDATE_DATE
     *
     * @param updateDate the value for t_folder.UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", folderId=").append(folderId);
        sb.append(", parentFolderId=").append(parentFolderId);
        sb.append(", folderGroup=").append(folderGroup);
        sb.append(", folderName=").append(folderName);
        sb.append(", s3FolderName=").append(s3FolderName);
        sb.append(", developerId=").append(developerId);
        sb.append(", mansionId=").append(mansionId);
        sb.append(", s3ObjectKey=").append(s3ObjectKey);
        sb.append(", deleteFlg=").append(deleteFlg);
        sb.append(", privateFlg=").append(privateFlg);
        sb.append(", explanatoryText=").append(explanatoryText);
        sb.append(", createUser=").append(createUser);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateDate=").append(updateDate);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TFolder other = (TFolder) that;
        return (this.getFolderId() == null ? other.getFolderId() == null : this.getFolderId().equals(other.getFolderId()))
            && (this.getParentFolderId() == null ? other.getParentFolderId() == null : this.getParentFolderId().equals(other.getParentFolderId()))
            && (this.getFolderGroup() == null ? other.getFolderGroup() == null : this.getFolderGroup().equals(other.getFolderGroup()))
            && (this.getFolderName() == null ? other.getFolderName() == null : this.getFolderName().equals(other.getFolderName()))
            && (this.getS3FolderName() == null ? other.getS3FolderName() == null : this.getS3FolderName().equals(other.getS3FolderName()))
            && (this.getDeveloperId() == null ? other.getDeveloperId() == null : this.getDeveloperId().equals(other.getDeveloperId()))
            && (this.getMansionId() == null ? other.getMansionId() == null : this.getMansionId().equals(other.getMansionId()))
            && (this.getS3ObjectKey() == null ? other.getS3ObjectKey() == null : this.getS3ObjectKey().equals(other.getS3ObjectKey()))
            && (this.getDeleteFlg() == null ? other.getDeleteFlg() == null : this.getDeleteFlg().equals(other.getDeleteFlg()))
            && (this.getPrivateFlg() == null ? other.getPrivateFlg() == null : this.getPrivateFlg().equals(other.getPrivateFlg()))
            && (this.getExplanatoryText() == null ? other.getExplanatoryText() == null : this.getExplanatoryText().equals(other.getExplanatoryText()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFolderId() == null) ? 0 : getFolderId().hashCode());
        result = prime * result + ((getParentFolderId() == null) ? 0 : getParentFolderId().hashCode());
        result = prime * result + ((getFolderGroup() == null) ? 0 : getFolderGroup().hashCode());
        result = prime * result + ((getFolderName() == null) ? 0 : getFolderName().hashCode());
        result = prime * result + ((getS3FolderName() == null) ? 0 : getS3FolderName().hashCode());
        result = prime * result + ((getDeveloperId() == null) ? 0 : getDeveloperId().hashCode());
        result = prime * result + ((getMansionId() == null) ? 0 : getMansionId().hashCode());
        result = prime * result + ((getS3ObjectKey() == null) ? 0 : getS3ObjectKey().hashCode());
        result = prime * result + ((getDeleteFlg() == null) ? 0 : getDeleteFlg().hashCode());
        result = prime * result + ((getPrivateFlg() == null) ? 0 : getPrivateFlg().hashCode());
        result = prime * result + ((getExplanatoryText() == null) ? 0 : getExplanatoryText().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }
}