package jp.co.fnj.storage.api.entity.model.generat;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class TFolderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    protected boolean forUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    public TFolderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    public boolean isForUpdate() {
        return this.forUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    public void setForUpdate(boolean forUpdate) {
        this.forUpdate = forUpdate;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFolderIdIsNull() {
            addCriterion("FOLDER_ID is null");
            return (Criteria) this;
        }

        public Criteria andFolderIdIsNotNull() {
            addCriterion("FOLDER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFolderIdEqualTo(String value) {
            addCriterion("FOLDER_ID =", value, "folderId");
            return (Criteria) this;
        }

        public Criteria andFolderIdNotEqualTo(String value) {
            addCriterion("FOLDER_ID <>", value, "folderId");
            return (Criteria) this;
        }

        public Criteria andFolderIdGreaterThan(String value) {
            addCriterion("FOLDER_ID >", value, "folderId");
            return (Criteria) this;
        }

        public Criteria andFolderIdGreaterThanOrEqualTo(String value) {
            addCriterion("FOLDER_ID >=", value, "folderId");
            return (Criteria) this;
        }

        public Criteria andFolderIdLessThan(String value) {
            addCriterion("FOLDER_ID <", value, "folderId");
            return (Criteria) this;
        }

        public Criteria andFolderIdLessThanOrEqualTo(String value) {
            addCriterion("FOLDER_ID <=", value, "folderId");
            return (Criteria) this;
        }

        public Criteria andFolderIdLike(String value) {
            addCriterion("FOLDER_ID like", value, "folderId");
            return (Criteria) this;
        }

        public Criteria andFolderIdNotLike(String value) {
            addCriterion("FOLDER_ID not like", value, "folderId");
            return (Criteria) this;
        }

        public Criteria andFolderIdIn(List<String> values) {
            addCriterion("FOLDER_ID in", values, "folderId");
            return (Criteria) this;
        }

        public Criteria andFolderIdNotIn(List<String> values) {
            addCriterion("FOLDER_ID not in", values, "folderId");
            return (Criteria) this;
        }

        public Criteria andFolderIdBetween(String value1, String value2) {
            addCriterion("FOLDER_ID between", value1, value2, "folderId");
            return (Criteria) this;
        }

        public Criteria andFolderIdNotBetween(String value1, String value2) {
            addCriterion("FOLDER_ID not between", value1, value2, "folderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdIsNull() {
            addCriterion("PARENT_FOLDER_ID is null");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdIsNotNull() {
            addCriterion("PARENT_FOLDER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdEqualTo(String value) {
            addCriterion("PARENT_FOLDER_ID =", value, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdNotEqualTo(String value) {
            addCriterion("PARENT_FOLDER_ID <>", value, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdGreaterThan(String value) {
            addCriterion("PARENT_FOLDER_ID >", value, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdGreaterThanOrEqualTo(String value) {
            addCriterion("PARENT_FOLDER_ID >=", value, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdLessThan(String value) {
            addCriterion("PARENT_FOLDER_ID <", value, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdLessThanOrEqualTo(String value) {
            addCriterion("PARENT_FOLDER_ID <=", value, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdLike(String value) {
            addCriterion("PARENT_FOLDER_ID like", value, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdNotLike(String value) {
            addCriterion("PARENT_FOLDER_ID not like", value, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdIn(List<String> values) {
            addCriterion("PARENT_FOLDER_ID in", values, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdNotIn(List<String> values) {
            addCriterion("PARENT_FOLDER_ID not in", values, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdBetween(String value1, String value2) {
            addCriterion("PARENT_FOLDER_ID between", value1, value2, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdNotBetween(String value1, String value2) {
            addCriterion("PARENT_FOLDER_ID not between", value1, value2, "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andFolderGroupIsNull() {
            addCriterion("FOLDER_GROUP is null");
            return (Criteria) this;
        }

        public Criteria andFolderGroupIsNotNull() {
            addCriterion("FOLDER_GROUP is not null");
            return (Criteria) this;
        }

        public Criteria andFolderGroupEqualTo(Integer value) {
            addCriterion("FOLDER_GROUP =", value, "folderGroup");
            return (Criteria) this;
        }

        public Criteria andFolderGroupNotEqualTo(Integer value) {
            addCriterion("FOLDER_GROUP <>", value, "folderGroup");
            return (Criteria) this;
        }

        public Criteria andFolderGroupGreaterThan(Integer value) {
            addCriterion("FOLDER_GROUP >", value, "folderGroup");
            return (Criteria) this;
        }

        public Criteria andFolderGroupGreaterThanOrEqualTo(Integer value) {
            addCriterion("FOLDER_GROUP >=", value, "folderGroup");
            return (Criteria) this;
        }

        public Criteria andFolderGroupLessThan(Integer value) {
            addCriterion("FOLDER_GROUP <", value, "folderGroup");
            return (Criteria) this;
        }

        public Criteria andFolderGroupLessThanOrEqualTo(Integer value) {
            addCriterion("FOLDER_GROUP <=", value, "folderGroup");
            return (Criteria) this;
        }

        public Criteria andFolderGroupIn(List<Integer> values) {
            addCriterion("FOLDER_GROUP in", values, "folderGroup");
            return (Criteria) this;
        }

        public Criteria andFolderGroupNotIn(List<Integer> values) {
            addCriterion("FOLDER_GROUP not in", values, "folderGroup");
            return (Criteria) this;
        }

        public Criteria andFolderGroupBetween(Integer value1, Integer value2) {
            addCriterion("FOLDER_GROUP between", value1, value2, "folderGroup");
            return (Criteria) this;
        }

        public Criteria andFolderGroupNotBetween(Integer value1, Integer value2) {
            addCriterion("FOLDER_GROUP not between", value1, value2, "folderGroup");
            return (Criteria) this;
        }

        public Criteria andFolderNameIsNull() {
            addCriterion("FOLDER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andFolderNameIsNotNull() {
            addCriterion("FOLDER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andFolderNameEqualTo(String value) {
            addCriterion("FOLDER_NAME =", value, "folderName");
            return (Criteria) this;
        }

        public Criteria andFolderNameNotEqualTo(String value) {
            addCriterion("FOLDER_NAME <>", value, "folderName");
            return (Criteria) this;
        }

        public Criteria andFolderNameGreaterThan(String value) {
            addCriterion("FOLDER_NAME >", value, "folderName");
            return (Criteria) this;
        }

        public Criteria andFolderNameGreaterThanOrEqualTo(String value) {
            addCriterion("FOLDER_NAME >=", value, "folderName");
            return (Criteria) this;
        }

        public Criteria andFolderNameLessThan(String value) {
            addCriterion("FOLDER_NAME <", value, "folderName");
            return (Criteria) this;
        }

        public Criteria andFolderNameLessThanOrEqualTo(String value) {
            addCriterion("FOLDER_NAME <=", value, "folderName");
            return (Criteria) this;
        }

        public Criteria andFolderNameLike(String value) {
            addCriterion("FOLDER_NAME like", value, "folderName");
            return (Criteria) this;
        }

        public Criteria andFolderNameNotLike(String value) {
            addCriterion("FOLDER_NAME not like", value, "folderName");
            return (Criteria) this;
        }

        public Criteria andFolderNameIn(List<String> values) {
            addCriterion("FOLDER_NAME in", values, "folderName");
            return (Criteria) this;
        }

        public Criteria andFolderNameNotIn(List<String> values) {
            addCriterion("FOLDER_NAME not in", values, "folderName");
            return (Criteria) this;
        }

        public Criteria andFolderNameBetween(String value1, String value2) {
            addCriterion("FOLDER_NAME between", value1, value2, "folderName");
            return (Criteria) this;
        }

        public Criteria andFolderNameNotBetween(String value1, String value2) {
            addCriterion("FOLDER_NAME not between", value1, value2, "folderName");
            return (Criteria) this;
        }

        public Criteria andS3FolderNameIsNull() {
            addCriterion("S3_FOLDER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andS3FolderNameIsNotNull() {
            addCriterion("S3_FOLDER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andS3FolderNameEqualTo(String value) {
            addCriterion("S3_FOLDER_NAME =", value, "s3FolderName");
            return (Criteria) this;
        }

        public Criteria andS3FolderNameNotEqualTo(String value) {
            addCriterion("S3_FOLDER_NAME <>", value, "s3FolderName");
            return (Criteria) this;
        }

        public Criteria andS3FolderNameGreaterThan(String value) {
            addCriterion("S3_FOLDER_NAME >", value, "s3FolderName");
            return (Criteria) this;
        }

        public Criteria andS3FolderNameGreaterThanOrEqualTo(String value) {
            addCriterion("S3_FOLDER_NAME >=", value, "s3FolderName");
            return (Criteria) this;
        }

        public Criteria andS3FolderNameLessThan(String value) {
            addCriterion("S3_FOLDER_NAME <", value, "s3FolderName");
            return (Criteria) this;
        }

        public Criteria andS3FolderNameLessThanOrEqualTo(String value) {
            addCriterion("S3_FOLDER_NAME <=", value, "s3FolderName");
            return (Criteria) this;
        }

        public Criteria andS3FolderNameLike(String value) {
            addCriterion("S3_FOLDER_NAME like", value, "s3FolderName");
            return (Criteria) this;
        }

        public Criteria andS3FolderNameNotLike(String value) {
            addCriterion("S3_FOLDER_NAME not like", value, "s3FolderName");
            return (Criteria) this;
        }

        public Criteria andS3FolderNameIn(List<String> values) {
            addCriterion("S3_FOLDER_NAME in", values, "s3FolderName");
            return (Criteria) this;
        }

        public Criteria andS3FolderNameNotIn(List<String> values) {
            addCriterion("S3_FOLDER_NAME not in", values, "s3FolderName");
            return (Criteria) this;
        }

        public Criteria andS3FolderNameBetween(String value1, String value2) {
            addCriterion("S3_FOLDER_NAME between", value1, value2, "s3FolderName");
            return (Criteria) this;
        }

        public Criteria andS3FolderNameNotBetween(String value1, String value2) {
            addCriterion("S3_FOLDER_NAME not between", value1, value2, "s3FolderName");
            return (Criteria) this;
        }

        public Criteria andDeveloperIdIsNull() {
            addCriterion("DEVELOPER_ID is null");
            return (Criteria) this;
        }

        public Criteria andDeveloperIdIsNotNull() {
            addCriterion("DEVELOPER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDeveloperIdEqualTo(String value) {
            addCriterion("DEVELOPER_ID =", value, "developerId");
            return (Criteria) this;
        }

        public Criteria andDeveloperIdNotEqualTo(String value) {
            addCriterion("DEVELOPER_ID <>", value, "developerId");
            return (Criteria) this;
        }

        public Criteria andDeveloperIdGreaterThan(String value) {
            addCriterion("DEVELOPER_ID >", value, "developerId");
            return (Criteria) this;
        }

        public Criteria andDeveloperIdGreaterThanOrEqualTo(String value) {
            addCriterion("DEVELOPER_ID >=", value, "developerId");
            return (Criteria) this;
        }

        public Criteria andDeveloperIdLessThan(String value) {
            addCriterion("DEVELOPER_ID <", value, "developerId");
            return (Criteria) this;
        }

        public Criteria andDeveloperIdLessThanOrEqualTo(String value) {
            addCriterion("DEVELOPER_ID <=", value, "developerId");
            return (Criteria) this;
        }

        public Criteria andDeveloperIdLike(String value) {
            addCriterion("DEVELOPER_ID like", value, "developerId");
            return (Criteria) this;
        }

        public Criteria andDeveloperIdNotLike(String value) {
            addCriterion("DEVELOPER_ID not like", value, "developerId");
            return (Criteria) this;
        }

        public Criteria andDeveloperIdIn(List<String> values) {
            addCriterion("DEVELOPER_ID in", values, "developerId");
            return (Criteria) this;
        }

        public Criteria andDeveloperIdNotIn(List<String> values) {
            addCriterion("DEVELOPER_ID not in", values, "developerId");
            return (Criteria) this;
        }

        public Criteria andDeveloperIdBetween(String value1, String value2) {
            addCriterion("DEVELOPER_ID between", value1, value2, "developerId");
            return (Criteria) this;
        }

        public Criteria andDeveloperIdNotBetween(String value1, String value2) {
            addCriterion("DEVELOPER_ID not between", value1, value2, "developerId");
            return (Criteria) this;
        }

        public Criteria andMansionIdIsNull() {
            addCriterion("MANSION_ID is null");
            return (Criteria) this;
        }

        public Criteria andMansionIdIsNotNull() {
            addCriterion("MANSION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMansionIdEqualTo(String value) {
            addCriterion("MANSION_ID =", value, "mansionId");
            return (Criteria) this;
        }

        public Criteria andMansionIdNotEqualTo(String value) {
            addCriterion("MANSION_ID <>", value, "mansionId");
            return (Criteria) this;
        }

        public Criteria andMansionIdGreaterThan(String value) {
            addCriterion("MANSION_ID >", value, "mansionId");
            return (Criteria) this;
        }

        public Criteria andMansionIdGreaterThanOrEqualTo(String value) {
            addCriterion("MANSION_ID >=", value, "mansionId");
            return (Criteria) this;
        }

        public Criteria andMansionIdLessThan(String value) {
            addCriterion("MANSION_ID <", value, "mansionId");
            return (Criteria) this;
        }

        public Criteria andMansionIdLessThanOrEqualTo(String value) {
            addCriterion("MANSION_ID <=", value, "mansionId");
            return (Criteria) this;
        }

        public Criteria andMansionIdLike(String value) {
            addCriterion("MANSION_ID like", value, "mansionId");
            return (Criteria) this;
        }

        public Criteria andMansionIdNotLike(String value) {
            addCriterion("MANSION_ID not like", value, "mansionId");
            return (Criteria) this;
        }

        public Criteria andMansionIdIn(List<String> values) {
            addCriterion("MANSION_ID in", values, "mansionId");
            return (Criteria) this;
        }

        public Criteria andMansionIdNotIn(List<String> values) {
            addCriterion("MANSION_ID not in", values, "mansionId");
            return (Criteria) this;
        }

        public Criteria andMansionIdBetween(String value1, String value2) {
            addCriterion("MANSION_ID between", value1, value2, "mansionId");
            return (Criteria) this;
        }

        public Criteria andMansionIdNotBetween(String value1, String value2) {
            addCriterion("MANSION_ID not between", value1, value2, "mansionId");
            return (Criteria) this;
        }

        public Criteria andS3ObjectKeyIsNull() {
            addCriterion("S3_OBJECT_KEY is null");
            return (Criteria) this;
        }

        public Criteria andS3ObjectKeyIsNotNull() {
            addCriterion("S3_OBJECT_KEY is not null");
            return (Criteria) this;
        }

        public Criteria andS3ObjectKeyEqualTo(String value) {
            addCriterion("S3_OBJECT_KEY =", value, "s3ObjectKey");
            return (Criteria) this;
        }

        public Criteria andS3ObjectKeyNotEqualTo(String value) {
            addCriterion("S3_OBJECT_KEY <>", value, "s3ObjectKey");
            return (Criteria) this;
        }

        public Criteria andS3ObjectKeyGreaterThan(String value) {
            addCriterion("S3_OBJECT_KEY >", value, "s3ObjectKey");
            return (Criteria) this;
        }

        public Criteria andS3ObjectKeyGreaterThanOrEqualTo(String value) {
            addCriterion("S3_OBJECT_KEY >=", value, "s3ObjectKey");
            return (Criteria) this;
        }

        public Criteria andS3ObjectKeyLessThan(String value) {
            addCriterion("S3_OBJECT_KEY <", value, "s3ObjectKey");
            return (Criteria) this;
        }

        public Criteria andS3ObjectKeyLessThanOrEqualTo(String value) {
            addCriterion("S3_OBJECT_KEY <=", value, "s3ObjectKey");
            return (Criteria) this;
        }

        public Criteria andS3ObjectKeyLike(String value) {
            addCriterion("S3_OBJECT_KEY like", value, "s3ObjectKey");
            return (Criteria) this;
        }

        public Criteria andS3ObjectKeyNotLike(String value) {
            addCriterion("S3_OBJECT_KEY not like", value, "s3ObjectKey");
            return (Criteria) this;
        }

        public Criteria andS3ObjectKeyIn(List<String> values) {
            addCriterion("S3_OBJECT_KEY in", values, "s3ObjectKey");
            return (Criteria) this;
        }

        public Criteria andS3ObjectKeyNotIn(List<String> values) {
            addCriterion("S3_OBJECT_KEY not in", values, "s3ObjectKey");
            return (Criteria) this;
        }

        public Criteria andS3ObjectKeyBetween(String value1, String value2) {
            addCriterion("S3_OBJECT_KEY between", value1, value2, "s3ObjectKey");
            return (Criteria) this;
        }

        public Criteria andS3ObjectKeyNotBetween(String value1, String value2) {
            addCriterion("S3_OBJECT_KEY not between", value1, value2, "s3ObjectKey");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIsNull() {
            addCriterion("DELETE_FLG is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIsNotNull() {
            addCriterion("DELETE_FLG is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgEqualTo(Boolean value) {
            addCriterion("DELETE_FLG =", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotEqualTo(Boolean value) {
            addCriterion("DELETE_FLG <>", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgGreaterThan(Boolean value) {
            addCriterion("DELETE_FLG >", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgGreaterThanOrEqualTo(Boolean value) {
            addCriterion("DELETE_FLG >=", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLessThan(Boolean value) {
            addCriterion("DELETE_FLG <", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLessThanOrEqualTo(Boolean value) {
            addCriterion("DELETE_FLG <=", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIn(List<Boolean> values) {
            addCriterion("DELETE_FLG in", values, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotIn(List<Boolean> values) {
            addCriterion("DELETE_FLG not in", values, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgBetween(Boolean value1, Boolean value2) {
            addCriterion("DELETE_FLG between", value1, value2, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotBetween(Boolean value1, Boolean value2) {
            addCriterion("DELETE_FLG not between", value1, value2, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andPrivateFlgIsNull() {
            addCriterion("PRIVATE_FLG is null");
            return (Criteria) this;
        }

        public Criteria andPrivateFlgIsNotNull() {
            addCriterion("PRIVATE_FLG is not null");
            return (Criteria) this;
        }

        public Criteria andPrivateFlgEqualTo(Boolean value) {
            addCriterion("PRIVATE_FLG =", value, "privateFlg");
            return (Criteria) this;
        }

        public Criteria andPrivateFlgNotEqualTo(Boolean value) {
            addCriterion("PRIVATE_FLG <>", value, "privateFlg");
            return (Criteria) this;
        }

        public Criteria andPrivateFlgGreaterThan(Boolean value) {
            addCriterion("PRIVATE_FLG >", value, "privateFlg");
            return (Criteria) this;
        }

        public Criteria andPrivateFlgGreaterThanOrEqualTo(Boolean value) {
            addCriterion("PRIVATE_FLG >=", value, "privateFlg");
            return (Criteria) this;
        }

        public Criteria andPrivateFlgLessThan(Boolean value) {
            addCriterion("PRIVATE_FLG <", value, "privateFlg");
            return (Criteria) this;
        }

        public Criteria andPrivateFlgLessThanOrEqualTo(Boolean value) {
            addCriterion("PRIVATE_FLG <=", value, "privateFlg");
            return (Criteria) this;
        }

        public Criteria andPrivateFlgIn(List<Boolean> values) {
            addCriterion("PRIVATE_FLG in", values, "privateFlg");
            return (Criteria) this;
        }

        public Criteria andPrivateFlgNotIn(List<Boolean> values) {
            addCriterion("PRIVATE_FLG not in", values, "privateFlg");
            return (Criteria) this;
        }

        public Criteria andPrivateFlgBetween(Boolean value1, Boolean value2) {
            addCriterion("PRIVATE_FLG between", value1, value2, "privateFlg");
            return (Criteria) this;
        }

        public Criteria andPrivateFlgNotBetween(Boolean value1, Boolean value2) {
            addCriterion("PRIVATE_FLG not between", value1, value2, "privateFlg");
            return (Criteria) this;
        }

        public Criteria andExplanatoryTextIsNull() {
            addCriterion("EXPLANATORY_TEXT is null");
            return (Criteria) this;
        }

        public Criteria andExplanatoryTextIsNotNull() {
            addCriterion("EXPLANATORY_TEXT is not null");
            return (Criteria) this;
        }

        public Criteria andExplanatoryTextEqualTo(String value) {
            addCriterion("EXPLANATORY_TEXT =", value, "explanatoryText");
            return (Criteria) this;
        }

        public Criteria andExplanatoryTextNotEqualTo(String value) {
            addCriterion("EXPLANATORY_TEXT <>", value, "explanatoryText");
            return (Criteria) this;
        }

        public Criteria andExplanatoryTextGreaterThan(String value) {
            addCriterion("EXPLANATORY_TEXT >", value, "explanatoryText");
            return (Criteria) this;
        }

        public Criteria andExplanatoryTextGreaterThanOrEqualTo(String value) {
            addCriterion("EXPLANATORY_TEXT >=", value, "explanatoryText");
            return (Criteria) this;
        }

        public Criteria andExplanatoryTextLessThan(String value) {
            addCriterion("EXPLANATORY_TEXT <", value, "explanatoryText");
            return (Criteria) this;
        }

        public Criteria andExplanatoryTextLessThanOrEqualTo(String value) {
            addCriterion("EXPLANATORY_TEXT <=", value, "explanatoryText");
            return (Criteria) this;
        }

        public Criteria andExplanatoryTextLike(String value) {
            addCriterion("EXPLANATORY_TEXT like", value, "explanatoryText");
            return (Criteria) this;
        }

        public Criteria andExplanatoryTextNotLike(String value) {
            addCriterion("EXPLANATORY_TEXT not like", value, "explanatoryText");
            return (Criteria) this;
        }

        public Criteria andExplanatoryTextIn(List<String> values) {
            addCriterion("EXPLANATORY_TEXT in", values, "explanatoryText");
            return (Criteria) this;
        }

        public Criteria andExplanatoryTextNotIn(List<String> values) {
            addCriterion("EXPLANATORY_TEXT not in", values, "explanatoryText");
            return (Criteria) this;
        }

        public Criteria andExplanatoryTextBetween(String value1, String value2) {
            addCriterion("EXPLANATORY_TEXT between", value1, value2, "explanatoryText");
            return (Criteria) this;
        }

        public Criteria andExplanatoryTextNotBetween(String value1, String value2) {
            addCriterion("EXPLANATORY_TEXT not between", value1, value2, "explanatoryText");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("CREATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("CREATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("CREATE_USER =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("CREATE_USER <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("CREATE_USER >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("CREATE_USER <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("CREATE_USER like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("CREATE_USER not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("CREATE_USER in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("CREATE_USER not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("CREATE_USER between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(LocalDateTime value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(LocalDateTime value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(LocalDateTime value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(LocalDateTime value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<LocalDateTime> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<LocalDateTime> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("UPDATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("UPDATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("UPDATE_USER =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("UPDATE_USER <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("UPDATE_USER >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("UPDATE_USER <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("UPDATE_USER like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("UPDATE_USER not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("UPDATE_USER in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("UPDATE_USER not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("UPDATE_USER between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(LocalDateTime value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(LocalDateTime value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(LocalDateTime value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(LocalDateTime value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<LocalDateTime> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<LocalDateTime> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andFolderIdLikeInsensitive(String value) {
            addCriterion("upper(FOLDER_ID) like", value.toUpperCase(), "folderId");
            return (Criteria) this;
        }

        public Criteria andParentFolderIdLikeInsensitive(String value) {
            addCriterion("upper(PARENT_FOLDER_ID) like", value.toUpperCase(), "parentFolderId");
            return (Criteria) this;
        }

        public Criteria andFolderNameLikeInsensitive(String value) {
            addCriterion("upper(FOLDER_NAME) like", value.toUpperCase(), "folderName");
            return (Criteria) this;
        }

        public Criteria andS3FolderNameLikeInsensitive(String value) {
            addCriterion("upper(S3_FOLDER_NAME) like", value.toUpperCase(), "s3FolderName");
            return (Criteria) this;
        }

        public Criteria andDeveloperIdLikeInsensitive(String value) {
            addCriterion("upper(DEVELOPER_ID) like", value.toUpperCase(), "developerId");
            return (Criteria) this;
        }

        public Criteria andMansionIdLikeInsensitive(String value) {
            addCriterion("upper(MANSION_ID) like", value.toUpperCase(), "mansionId");
            return (Criteria) this;
        }

        public Criteria andS3ObjectKeyLikeInsensitive(String value) {
            addCriterion("upper(S3_OBJECT_KEY) like", value.toUpperCase(), "s3ObjectKey");
            return (Criteria) this;
        }

        public Criteria andExplanatoryTextLikeInsensitive(String value) {
            addCriterion("upper(EXPLANATORY_TEXT) like", value.toUpperCase(), "explanatoryText");
            return (Criteria) this;
        }

        public Criteria andCreateUserLikeInsensitive(String value) {
            addCriterion("upper(CREATE_USER) like", value.toUpperCase(), "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLikeInsensitive(String value) {
            addCriterion("upper(UPDATE_USER) like", value.toUpperCase(), "updateUser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_folder
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}