package jp.co.fnj.storage.api.entity.model.generat;

public class TFullTextSearch extends TFullTextSearchKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_FULL_TEXT_SEARCH.TEXT_DATA
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private String textData;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_FULL_TEXT_SEARCH.TEXT_DATA
	 * @return  the value of T_FULL_TEXT_SEARCH.TEXT_DATA
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public String getTextData() {
		return textData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_FULL_TEXT_SEARCH.TEXT_DATA
	 * @param textData  the value for T_FULL_TEXT_SEARCH.TEXT_DATA
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setTextData(String textData) {
		this.textData = textData == null ? null : textData.trim();
	}
}