package jp.co.fnj.storage.api.entity.model.generat;

import java.io.Serializable;

public class TFullTextSearchKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_full_text_search.FILE_ID
     *
     * @mbg.generated
     */
    private String fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_full_text_search.FILE_NO
     *
     * @mbg.generated
     */
    private Integer fileNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_full_text_search
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_full_text_search.FILE_ID
     *
     * @return the value of t_full_text_search.FILE_ID
     *
     * @mbg.generated
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_full_text_search.FILE_ID
     *
     * @param fileId the value for t_full_text_search.FILE_ID
     *
     * @mbg.generated
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_full_text_search.FILE_NO
     *
     * @return the value of t_full_text_search.FILE_NO
     *
     * @mbg.generated
     */
    public Integer getFileNo() {
        return fileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_full_text_search.FILE_NO
     *
     * @param fileNo the value for t_full_text_search.FILE_NO
     *
     * @mbg.generated
     */
    public void setFileNo(Integer fileNo) {
        this.fileNo = fileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_full_text_search
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fileId=").append(fileId);
        sb.append(", fileNo=").append(fileNo);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_full_text_search
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TFullTextSearchKey other = (TFullTextSearchKey) that;
        return (this.getFileId() == null ? other.getFileId() == null : this.getFileId().equals(other.getFileId()))
            && (this.getFileNo() == null ? other.getFileNo() == null : this.getFileNo().equals(other.getFileNo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_full_text_search
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFileId() == null) ? 0 : getFileId().hashCode());
        result = prime * result + ((getFileNo() == null) ? 0 : getFileNo().hashCode());
        return result;
    }
}