package jp.co.fnj.storage.api.entity.model.generat;

public class TFullTextSearchKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_FULL_TEXT_SEARCH.FILE_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private String fileId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_FULL_TEXT_SEARCH.FILE_NO
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private Integer fileNo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_FULL_TEXT_SEARCH.FILE_ID
	 * @return  the value of T_FULL_TEXT_SEARCH.FILE_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public String getFileId() {
		return fileId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_FULL_TEXT_SEARCH.FILE_ID
	 * @param fileId  the value for T_FULL_TEXT_SEARCH.FILE_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setFileId(String fileId) {
		this.fileId = fileId == null ? null : fileId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_FULL_TEXT_SEARCH.FILE_NO
	 * @return  the value of T_FULL_TEXT_SEARCH.FILE_NO
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public Integer getFileNo() {
		return fileNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_FULL_TEXT_SEARCH.FILE_NO
	 * @param fileNo  the value for T_FULL_TEXT_SEARCH.FILE_NO
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setFileNo(Integer fileNo) {
		this.fileNo = fileNo;
	}
}