package jp.co.fnj.storage.api.entity.model.generat;

import java.util.ArrayList;
import java.util.List;

public class TFullTextSearchExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table T_FULL_TEXT_SEARCH
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table T_FULL_TEXT_SEARCH
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table T_FULL_TEXT_SEARCH
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_FULL_TEXT_SEARCH
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public TFullTextSearchExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_FULL_TEXT_SEARCH
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_FULL_TEXT_SEARCH
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_FULL_TEXT_SEARCH
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_FULL_TEXT_SEARCH
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_FULL_TEXT_SEARCH
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_FULL_TEXT_SEARCH
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_FULL_TEXT_SEARCH
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_FULL_TEXT_SEARCH
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_FULL_TEXT_SEARCH
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_FULL_TEXT_SEARCH
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table T_FULL_TEXT_SEARCH
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andFileIdIsNull() {
			addCriterion("FILE_ID is null");
			return (Criteria) this;
		}

		public Criteria andFileIdIsNotNull() {
			addCriterion("FILE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andFileIdEqualTo(String value) {
			addCriterion("FILE_ID =", value, "fileId");
			return (Criteria) this;
		}

		public Criteria andFileIdNotEqualTo(String value) {
			addCriterion("FILE_ID <>", value, "fileId");
			return (Criteria) this;
		}

		public Criteria andFileIdGreaterThan(String value) {
			addCriterion("FILE_ID >", value, "fileId");
			return (Criteria) this;
		}

		public Criteria andFileIdGreaterThanOrEqualTo(String value) {
			addCriterion("FILE_ID >=", value, "fileId");
			return (Criteria) this;
		}

		public Criteria andFileIdLessThan(String value) {
			addCriterion("FILE_ID <", value, "fileId");
			return (Criteria) this;
		}

		public Criteria andFileIdLessThanOrEqualTo(String value) {
			addCriterion("FILE_ID <=", value, "fileId");
			return (Criteria) this;
		}

		public Criteria andFileIdLike(String value) {
			addCriterion("FILE_ID like", value, "fileId");
			return (Criteria) this;
		}

		public Criteria andFileIdNotLike(String value) {
			addCriterion("FILE_ID not like", value, "fileId");
			return (Criteria) this;
		}

		public Criteria andFileIdIn(List<String> values) {
			addCriterion("FILE_ID in", values, "fileId");
			return (Criteria) this;
		}

		public Criteria andFileIdNotIn(List<String> values) {
			addCriterion("FILE_ID not in", values, "fileId");
			return (Criteria) this;
		}

		public Criteria andFileIdBetween(String value1, String value2) {
			addCriterion("FILE_ID between", value1, value2, "fileId");
			return (Criteria) this;
		}

		public Criteria andFileIdNotBetween(String value1, String value2) {
			addCriterion("FILE_ID not between", value1, value2, "fileId");
			return (Criteria) this;
		}

		public Criteria andFileNoIsNull() {
			addCriterion("FILE_NO is null");
			return (Criteria) this;
		}

		public Criteria andFileNoIsNotNull() {
			addCriterion("FILE_NO is not null");
			return (Criteria) this;
		}

		public Criteria andFileNoEqualTo(Integer value) {
			addCriterion("FILE_NO =", value, "fileNo");
			return (Criteria) this;
		}

		public Criteria andFileNoNotEqualTo(Integer value) {
			addCriterion("FILE_NO <>", value, "fileNo");
			return (Criteria) this;
		}

		public Criteria andFileNoGreaterThan(Integer value) {
			addCriterion("FILE_NO >", value, "fileNo");
			return (Criteria) this;
		}

		public Criteria andFileNoGreaterThanOrEqualTo(Integer value) {
			addCriterion("FILE_NO >=", value, "fileNo");
			return (Criteria) this;
		}

		public Criteria andFileNoLessThan(Integer value) {
			addCriterion("FILE_NO <", value, "fileNo");
			return (Criteria) this;
		}

		public Criteria andFileNoLessThanOrEqualTo(Integer value) {
			addCriterion("FILE_NO <=", value, "fileNo");
			return (Criteria) this;
		}

		public Criteria andFileNoIn(List<Integer> values) {
			addCriterion("FILE_NO in", values, "fileNo");
			return (Criteria) this;
		}

		public Criteria andFileNoNotIn(List<Integer> values) {
			addCriterion("FILE_NO not in", values, "fileNo");
			return (Criteria) this;
		}

		public Criteria andFileNoBetween(Integer value1, Integer value2) {
			addCriterion("FILE_NO between", value1, value2, "fileNo");
			return (Criteria) this;
		}

		public Criteria andFileNoNotBetween(Integer value1, Integer value2) {
			addCriterion("FILE_NO not between", value1, value2, "fileNo");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table T_FULL_TEXT_SEARCH
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_FULL_TEXT_SEARCH
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 05 22:31:31 JST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}