package jp.co.fnj.storage.api.entity.model.generat;

import java.io.Serializable;

public class TFullTextSearch extends TFullTextSearchKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_FULL_TEXT_SEARCH.TEXT_DATA
     *
     * @mbg.generated
     */
    private String textData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_FULL_TEXT_SEARCH
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FULL_TEXT_SEARCH.TEXT_DATA
     *
     * @return the value of T_FULL_TEXT_SEARCH.TEXT_DATA
     *
     * @mbg.generated
     */
    public String getTextData() {
        return textData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FULL_TEXT_SEARCH.TEXT_DATA
     *
     * @param textData the value for T_FULL_TEXT_SEARCH.TEXT_DATA
     *
     * @mbg.generated
     */
    public void setTextData(String textData) {
        this.textData = textData == null ? null : textData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FULL_TEXT_SEARCH
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", textData=").append(textData);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FULL_TEXT_SEARCH
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TFullTextSearch other = (TFullTextSearch) that;
        return (this.getFileId() == null ? other.getFileId() == null : this.getFileId().equals(other.getFileId()))
            && (this.getFileNo() == null ? other.getFileNo() == null : this.getFileNo().equals(other.getFileNo()))
            && (this.getTextData() == null ? other.getTextData() == null : this.getTextData().equals(other.getTextData()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FULL_TEXT_SEARCH
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFileId() == null) ? 0 : getFileId().hashCode());
        result = prime * result + ((getFileNo() == null) ? 0 : getFileNo().hashCode());
        result = prime * result + ((getTextData() == null) ? 0 : getTextData().hashCode());
        return result;
    }
}