package jp.co.fnj.storage.api.entity.model.generat;

import java.time.LocalDateTime;

public class TSequence {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_SEQUENCE.ID_NAME
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private String idName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_SEQUENCE.SEQUENCE_VALUE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private Long sequenceValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_SEQUENCE.CREATE_USER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_SEQUENCE.CREATE_DATE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private LocalDateTime createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_SEQUENCE.UPDATE_USER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private String updateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_SEQUENCE.UPDATE_DATE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private LocalDateTime updateDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_SEQUENCE.ID_NAME
	 * @return  the value of T_SEQUENCE.ID_NAME
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public String getIdName() {
		return idName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_SEQUENCE.ID_NAME
	 * @param idName  the value for T_SEQUENCE.ID_NAME
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setIdName(String idName) {
		this.idName = idName == null ? null : idName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_SEQUENCE.SEQUENCE_VALUE
	 * @return  the value of T_SEQUENCE.SEQUENCE_VALUE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public Long getSequenceValue() {
		return sequenceValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_SEQUENCE.SEQUENCE_VALUE
	 * @param sequenceValue  the value for T_SEQUENCE.SEQUENCE_VALUE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setSequenceValue(Long sequenceValue) {
		this.sequenceValue = sequenceValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_SEQUENCE.CREATE_USER
	 * @return  the value of T_SEQUENCE.CREATE_USER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_SEQUENCE.CREATE_USER
	 * @param createUser  the value for T_SEQUENCE.CREATE_USER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser == null ? null : createUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_SEQUENCE.CREATE_DATE
	 * @return  the value of T_SEQUENCE.CREATE_DATE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public LocalDateTime getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_SEQUENCE.CREATE_DATE
	 * @param createDate  the value for T_SEQUENCE.CREATE_DATE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setCreateDate(LocalDateTime createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_SEQUENCE.UPDATE_USER
	 * @return  the value of T_SEQUENCE.UPDATE_USER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_SEQUENCE.UPDATE_USER
	 * @param updateUser  the value for T_SEQUENCE.UPDATE_USER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser == null ? null : updateUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_SEQUENCE.UPDATE_DATE
	 * @return  the value of T_SEQUENCE.UPDATE_DATE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public LocalDateTime getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_SEQUENCE.UPDATE_DATE
	 * @param updateDate  the value for T_SEQUENCE.UPDATE_DATE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setUpdateDate(LocalDateTime updateDate) {
		this.updateDate = updateDate;
	}
}