package jp.co.fnj.storage.api.entity.model.generat;

import java.io.Serializable;
import java.time.LocalDateTime;

public class TSortOrder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SORT_ORDER.SORT_ORDER_ID
     *
     * @mbg.generated
     */
    private Integer sortOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SORT_ORDER.PARENT_FOLDER_ID
     *
     * @mbg.generated
     */
    private String parentFolderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SORT_ORDER.FILE_ID
     *
     * @mbg.generated
     */
    private String fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SORT_ORDER.FOLDER_ID
     *
     * @mbg.generated
     */
    private String folderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SORT_ORDER.SORT_ORDER
     *
     * @mbg.generated
     */
    private Integer sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SORT_ORDER.CREATE_USER
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SORT_ORDER.CREATE_DATE
     *
     * @mbg.generated
     */
    private LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SORT_ORDER.UPDATE_USER
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SORT_ORDER.UPDATE_DATE
     *
     * @mbg.generated
     */
    private LocalDateTime updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_SORT_ORDER
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SORT_ORDER.SORT_ORDER_ID
     *
     * @return the value of T_SORT_ORDER.SORT_ORDER_ID
     *
     * @mbg.generated
     */
    public Integer getSortOrderId() {
        return sortOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SORT_ORDER.SORT_ORDER_ID
     *
     * @param sortOrderId the value for T_SORT_ORDER.SORT_ORDER_ID
     *
     * @mbg.generated
     */
    public void setSortOrderId(Integer sortOrderId) {
        this.sortOrderId = sortOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SORT_ORDER.PARENT_FOLDER_ID
     *
     * @return the value of T_SORT_ORDER.PARENT_FOLDER_ID
     *
     * @mbg.generated
     */
    public String getParentFolderId() {
        return parentFolderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SORT_ORDER.PARENT_FOLDER_ID
     *
     * @param parentFolderId the value for T_SORT_ORDER.PARENT_FOLDER_ID
     *
     * @mbg.generated
     */
    public void setParentFolderId(String parentFolderId) {
        this.parentFolderId = parentFolderId == null ? null : parentFolderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SORT_ORDER.FILE_ID
     *
     * @return the value of T_SORT_ORDER.FILE_ID
     *
     * @mbg.generated
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SORT_ORDER.FILE_ID
     *
     * @param fileId the value for T_SORT_ORDER.FILE_ID
     *
     * @mbg.generated
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SORT_ORDER.FOLDER_ID
     *
     * @return the value of T_SORT_ORDER.FOLDER_ID
     *
     * @mbg.generated
     */
    public String getFolderId() {
        return folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SORT_ORDER.FOLDER_ID
     *
     * @param folderId the value for T_SORT_ORDER.FOLDER_ID
     *
     * @mbg.generated
     */
    public void setFolderId(String folderId) {
        this.folderId = folderId == null ? null : folderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SORT_ORDER.SORT_ORDER
     *
     * @return the value of T_SORT_ORDER.SORT_ORDER
     *
     * @mbg.generated
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SORT_ORDER.SORT_ORDER
     *
     * @param sortOrder the value for T_SORT_ORDER.SORT_ORDER
     *
     * @mbg.generated
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SORT_ORDER.CREATE_USER
     *
     * @return the value of T_SORT_ORDER.CREATE_USER
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SORT_ORDER.CREATE_USER
     *
     * @param createUser the value for T_SORT_ORDER.CREATE_USER
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SORT_ORDER.CREATE_DATE
     *
     * @return the value of T_SORT_ORDER.CREATE_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SORT_ORDER.CREATE_DATE
     *
     * @param createDate the value for T_SORT_ORDER.CREATE_DATE
     *
     * @mbg.generated
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SORT_ORDER.UPDATE_USER
     *
     * @return the value of T_SORT_ORDER.UPDATE_USER
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SORT_ORDER.UPDATE_USER
     *
     * @param updateUser the value for T_SORT_ORDER.UPDATE_USER
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SORT_ORDER.UPDATE_DATE
     *
     * @return the value of T_SORT_ORDER.UPDATE_DATE
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SORT_ORDER.UPDATE_DATE
     *
     * @param updateDate the value for T_SORT_ORDER.UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SORT_ORDER
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sortOrderId=").append(sortOrderId);
        sb.append(", parentFolderId=").append(parentFolderId);
        sb.append(", fileId=").append(fileId);
        sb.append(", folderId=").append(folderId);
        sb.append(", sortOrder=").append(sortOrder);
        sb.append(", createUser=").append(createUser);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", updateDate=").append(updateDate);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SORT_ORDER
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TSortOrder other = (TSortOrder) that;
        return (this.getSortOrderId() == null ? other.getSortOrderId() == null : this.getSortOrderId().equals(other.getSortOrderId()))
            && (this.getParentFolderId() == null ? other.getParentFolderId() == null : this.getParentFolderId().equals(other.getParentFolderId()))
            && (this.getFileId() == null ? other.getFileId() == null : this.getFileId().equals(other.getFileId()))
            && (this.getFolderId() == null ? other.getFolderId() == null : this.getFolderId().equals(other.getFolderId()))
            && (this.getSortOrder() == null ? other.getSortOrder() == null : this.getSortOrder().equals(other.getSortOrder()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SORT_ORDER
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSortOrderId() == null) ? 0 : getSortOrderId().hashCode());
        result = prime * result + ((getParentFolderId() == null) ? 0 : getParentFolderId().hashCode());
        result = prime * result + ((getFileId() == null) ? 0 : getFileId().hashCode());
        result = prime * result + ((getFolderId() == null) ? 0 : getFolderId().hashCode());
        result = prime * result + ((getSortOrder() == null) ? 0 : getSortOrder().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }
}