package jp.co.fnj.storage.api.entity.model.generat;

import java.time.LocalDateTime;

public class TSortOrder {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_SORT_ORDER.SORT_ORDER_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private Integer sortOrderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_SORT_ORDER.PARENT_FOLDER_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private String parentFolderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_SORT_ORDER.FILE_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private String fileId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_SORT_ORDER.FOLDER_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private String folderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_SORT_ORDER.SORT_ORDER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private Integer sortOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_SORT_ORDER.CREATE_USER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private String createUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_SORT_ORDER.CREATE_DATE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private LocalDateTime createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_SORT_ORDER.UPDATE_USER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private String updateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column T_SORT_ORDER.UPDATE_DATE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	private LocalDateTime updateDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_SORT_ORDER.SORT_ORDER_ID
	 * @return  the value of T_SORT_ORDER.SORT_ORDER_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public Integer getSortOrderId() {
		return sortOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_SORT_ORDER.SORT_ORDER_ID
	 * @param sortOrderId  the value for T_SORT_ORDER.SORT_ORDER_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setSortOrderId(Integer sortOrderId) {
		this.sortOrderId = sortOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_SORT_ORDER.PARENT_FOLDER_ID
	 * @return  the value of T_SORT_ORDER.PARENT_FOLDER_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public String getParentFolderId() {
		return parentFolderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_SORT_ORDER.PARENT_FOLDER_ID
	 * @param parentFolderId  the value for T_SORT_ORDER.PARENT_FOLDER_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setParentFolderId(String parentFolderId) {
		this.parentFolderId = parentFolderId == null ? null : parentFolderId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_SORT_ORDER.FILE_ID
	 * @return  the value of T_SORT_ORDER.FILE_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public String getFileId() {
		return fileId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_SORT_ORDER.FILE_ID
	 * @param fileId  the value for T_SORT_ORDER.FILE_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setFileId(String fileId) {
		this.fileId = fileId == null ? null : fileId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_SORT_ORDER.FOLDER_ID
	 * @return  the value of T_SORT_ORDER.FOLDER_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public String getFolderId() {
		return folderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_SORT_ORDER.FOLDER_ID
	 * @param folderId  the value for T_SORT_ORDER.FOLDER_ID
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setFolderId(String folderId) {
		this.folderId = folderId == null ? null : folderId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_SORT_ORDER.SORT_ORDER
	 * @return  the value of T_SORT_ORDER.SORT_ORDER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public Integer getSortOrder() {
		return sortOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_SORT_ORDER.SORT_ORDER
	 * @param sortOrder  the value for T_SORT_ORDER.SORT_ORDER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_SORT_ORDER.CREATE_USER
	 * @return  the value of T_SORT_ORDER.CREATE_USER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_SORT_ORDER.CREATE_USER
	 * @param createUser  the value for T_SORT_ORDER.CREATE_USER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser == null ? null : createUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_SORT_ORDER.CREATE_DATE
	 * @return  the value of T_SORT_ORDER.CREATE_DATE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public LocalDateTime getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_SORT_ORDER.CREATE_DATE
	 * @param createDate  the value for T_SORT_ORDER.CREATE_DATE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setCreateDate(LocalDateTime createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_SORT_ORDER.UPDATE_USER
	 * @return  the value of T_SORT_ORDER.UPDATE_USER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_SORT_ORDER.UPDATE_USER
	 * @param updateUser  the value for T_SORT_ORDER.UPDATE_USER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser == null ? null : updateUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column T_SORT_ORDER.UPDATE_DATE
	 * @return  the value of T_SORT_ORDER.UPDATE_DATE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public LocalDateTime getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column T_SORT_ORDER.UPDATE_DATE
	 * @param updateDate  the value for T_SORT_ORDER.UPDATE_DATE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	public void setUpdateDate(LocalDateTime updateDate) {
		this.updateDate = updateDate;
	}
}