package jp.co.fnj.storage.entity.mapper.generat;

import java.util.List;
import jp.co.fnj.storage.entity.model.generat.TFile;
import jp.co.fnj.storage.entity.model.generat.TFileExample;
import org.apache.ibatis.annotations.Param;

public interface TFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    int countByExample(TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    int deleteByExample(TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    int deleteByPrimaryKey(String fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    int insert(TFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    int insertSelective(TFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    List<TFile> selectByExample(TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    TFile selectByPrimaryKey(String fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    int updateByExampleSelective(@Param("record") TFile record, @Param("example") TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    int updateByExample(@Param("record") TFile record, @Param("example") TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    int updateByPrimaryKeySelective(TFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    int updateByPrimaryKey(TFile record);
}