package jp.co.fnj.storage.entity.mapper.generat;

import java.util.List;
import jp.co.fnj.storage.entity.model.generat.TFullTextSearch;
import jp.co.fnj.storage.entity.model.generat.TFullTextSearchExample;
import jp.co.fnj.storage.entity.model.generat.TFullTextSearchKey;
import org.apache.ibatis.annotations.Param;

public interface TFullTextSearchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_full_text_search
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    int countByExample(TFullTextSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_full_text_search
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    int deleteByExample(TFullTextSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_full_text_search
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    int deleteByPrimaryKey(TFullTextSearchKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_full_text_search
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    int insert(TFullTextSearch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_full_text_search
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    int insertSelective(TFullTextSearch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_full_text_search
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    List<TFullTextSearch> selectByExampleWithBLOBs(TFullTextSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_full_text_search
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    List<TFullTextSearch> selectByExample(TFullTextSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_full_text_search
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    TFullTextSearch selectByPrimaryKey(TFullTextSearchKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_full_text_search
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    int updateByExampleSelective(@Param("record") TFullTextSearch record, @Param("example") TFullTextSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_full_text_search
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") TFullTextSearch record, @Param("example") TFullTextSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_full_text_search
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    int updateByExample(@Param("record") TFullTextSearch record, @Param("example") TFullTextSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_full_text_search
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    int updateByPrimaryKeySelective(TFullTextSearch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_full_text_search
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    int updateByPrimaryKeyWithBLOBs(TFullTextSearch record);
}