package jp.co.fnj.storage.entity.mapper.generat;

import java.util.List;
import jp.co.fnj.storage.entity.model.generat.TSequence;
import jp.co.fnj.storage.entity.model.generat.TSequenceExample;
import org.apache.ibatis.annotations.Param;

public interface TSequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sequence
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    int countByExample(TSequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sequence
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    int deleteByExample(TSequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sequence
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    int deleteByPrimaryKey(String idName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sequence
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    int insert(TSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sequence
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    int insertSelective(TSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sequence
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    List<TSequence> selectByExample(TSequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sequence
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    TSequence selectByPrimaryKey(String idName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sequence
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    int updateByExampleSelective(@Param("record") TSequence record, @Param("example") TSequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sequence
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    int updateByExample(@Param("record") TSequence record, @Param("example") TSequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sequence
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    int updateByPrimaryKeySelective(TSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sequence
     *
     * @mbggenerated Wed Nov 06 14:03:48 JST 2019
     */
    int updateByPrimaryKey(TSequence record);
}