package jp.co.fnj.storage.api.entity.mapper.generat;

import java.util.List;
import jp.co.fnj.storage.api.entity.model.generat.TBookmark;
import jp.co.fnj.storage.api.entity.model.generat.TBookmarkExample;
import org.apache.ibatis.annotations.Param;

public interface TBookmarkMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_BOOKMARK
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	long countByExample(TBookmarkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_BOOKMARK
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	int deleteByExample(TBookmarkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_BOOKMARK
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	int deleteByPrimaryKey(Integer bookmarkId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_BOOKMARK
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	int insert(TBookmark record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_BOOKMARK
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	int insertSelective(TBookmark record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_BOOKMARK
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	List<TBookmark> selectByExample(TBookmarkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_BOOKMARK
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	TBookmark selectByPrimaryKey(Integer bookmarkId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_BOOKMARK
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	int updateByExampleSelective(@Param("record") TBookmark record, @Param("example") TBookmarkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_BOOKMARK
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	int updateByExample(@Param("record") TBookmark record, @Param("example") TBookmarkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_BOOKMARK
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	int updateByPrimaryKeySelective(TBookmark record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_BOOKMARK
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	int updateByPrimaryKey(TBookmark record);
}