package jp.co.fnj.storage.api.entity.mapper.generat;

import java.util.List;
import jp.co.fnj.storage.api.entity.model.generat.TBookmark;
import jp.co.fnj.storage.api.entity.model.generat.TBookmarkExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface TBookmarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookmark
     *
     * @mbg.generated
     */
    long countByExample(TBookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookmark
     *
     * @mbg.generated
     */
    int deleteByExample(TBookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookmark
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String bookmarkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookmark
     *
     * @mbg.generated
     */
    int insert(TBookmark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookmark
     *
     * @mbg.generated
     */
    int insertSelective(TBookmark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookmark
     *
     * @mbg.generated
     */
    List<TBookmark> selectByExampleWithRowbounds(TBookmarkExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookmark
     *
     * @mbg.generated
     */
    List<TBookmark> selectByExample(TBookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookmark
     *
     * @mbg.generated
     */
    TBookmark selectByPrimaryKey(String bookmarkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookmark
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TBookmark record, @Param("example") TBookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookmark
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TBookmark record, @Param("example") TBookmarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookmark
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TBookmark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bookmark
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TBookmark record);
}