package jp.co.fnj.storage.api.entity.mapper.generat;

import java.util.List;
import jp.co.fnj.storage.api.entity.model.generat.TExternalServiceObject;
import jp.co.fnj.storage.api.entity.model.generat.TExternalServiceObjectExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface TExternalServiceObjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXTERNAL_SERVICE_OBJECT
     *
     * @mbg.generated
     */
    long countByExample(TExternalServiceObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXTERNAL_SERVICE_OBJECT
     *
     * @mbg.generated
     */
    int deleteByExample(TExternalServiceObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXTERNAL_SERVICE_OBJECT
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXTERNAL_SERVICE_OBJECT
     *
     * @mbg.generated
     */
    int insert(TExternalServiceObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXTERNAL_SERVICE_OBJECT
     *
     * @mbg.generated
     */
    int insertSelective(TExternalServiceObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXTERNAL_SERVICE_OBJECT
     *
     * @mbg.generated
     */
    List<TExternalServiceObject> selectByExampleWithRowbounds(TExternalServiceObjectExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXTERNAL_SERVICE_OBJECT
     *
     * @mbg.generated
     */
    List<TExternalServiceObject> selectByExample(TExternalServiceObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXTERNAL_SERVICE_OBJECT
     *
     * @mbg.generated
     */
    TExternalServiceObject selectByPrimaryKey(String fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXTERNAL_SERVICE_OBJECT
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TExternalServiceObject record, @Param("example") TExternalServiceObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXTERNAL_SERVICE_OBJECT
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TExternalServiceObject record, @Param("example") TExternalServiceObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXTERNAL_SERVICE_OBJECT
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TExternalServiceObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EXTERNAL_SERVICE_OBJECT
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TExternalServiceObject record);
}