package jp.co.fnj.storage.api.entity.mapper.generat;

import java.util.List;
import jp.co.fnj.storage.api.entity.model.generat.TFile;
import jp.co.fnj.storage.api.entity.model.generat.TFileExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface TFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE
     *
     * @mbg.generated
     */
    long countByExample(TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE
     *
     * @mbg.generated
     */
    int deleteByExample(TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE
     *
     * @mbg.generated
     */
    int insert(TFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE
     *
     * @mbg.generated
     */
    int insertSelective(TFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE
     *
     * @mbg.generated
     */
    List<TFile> selectByExampleWithRowbounds(TFileExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE
     *
     * @mbg.generated
     */
    List<TFile> selectByExample(TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE
     *
     * @mbg.generated
     */
    TFile selectByPrimaryKey(String fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TFile record, @Param("example") TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TFile record, @Param("example") TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FILE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TFile record);
}