package jp.co.fnj.storage.api.entity.mapper.generat;

import java.util.List;
import jp.co.fnj.storage.api.entity.model.generat.TFolder;
import jp.co.fnj.storage.api.entity.model.generat.TFolderExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface TFolderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    long countByExample(TFolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    int deleteByExample(TFolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String folderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    int insert(TFolder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    int insertSelective(TFolder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    List<TFolder> selectByExampleWithRowbounds(TFolderExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    List<TFolder> selectByExample(TFolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    TFolder selectByPrimaryKey(String folderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TFolder record, @Param("example") TFolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TFolder record, @Param("example") TFolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TFolder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_folder
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TFolder record);
}