package jp.co.fnj.storage.api.entity.mapper.generat;

import java.util.List;
import jp.co.fnj.storage.api.entity.model.generat.TFullTextSearch;
import jp.co.fnj.storage.api.entity.model.generat.TFullTextSearchExample;
import jp.co.fnj.storage.api.entity.model.generat.TFullTextSearchKey;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface TFullTextSearchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FULL_TEXT_SEARCH
     *
     * @mbg.generated
     */
    long countByExample(TFullTextSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FULL_TEXT_SEARCH
     *
     * @mbg.generated
     */
    int deleteByExample(TFullTextSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FULL_TEXT_SEARCH
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TFullTextSearchKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FULL_TEXT_SEARCH
     *
     * @mbg.generated
     */
    int insert(TFullTextSearch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FULL_TEXT_SEARCH
     *
     * @mbg.generated
     */
    int insertSelective(TFullTextSearch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FULL_TEXT_SEARCH
     *
     * @mbg.generated
     */
    List<TFullTextSearch> selectByExampleWithBLOBsWithRowbounds(TFullTextSearchExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FULL_TEXT_SEARCH
     *
     * @mbg.generated
     */
    List<TFullTextSearch> selectByExampleWithBLOBs(TFullTextSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FULL_TEXT_SEARCH
     *
     * @mbg.generated
     */
    List<TFullTextSearch> selectByExampleWithRowbounds(TFullTextSearchExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FULL_TEXT_SEARCH
     *
     * @mbg.generated
     */
    List<TFullTextSearch> selectByExample(TFullTextSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FULL_TEXT_SEARCH
     *
     * @mbg.generated
     */
    TFullTextSearch selectByPrimaryKey(TFullTextSearchKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FULL_TEXT_SEARCH
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TFullTextSearch record, @Param("example") TFullTextSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FULL_TEXT_SEARCH
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TFullTextSearch record, @Param("example") TFullTextSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FULL_TEXT_SEARCH
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TFullTextSearch record, @Param("example") TFullTextSearchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FULL_TEXT_SEARCH
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TFullTextSearch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_FULL_TEXT_SEARCH
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TFullTextSearch record);
}