package jp.co.fnj.storage.api.entity.mapper.generat;

import java.util.List;
import jp.co.fnj.storage.api.entity.model.generat.TSequence;
import jp.co.fnj.storage.api.entity.model.generat.TSequenceExample;
import org.apache.ibatis.annotations.Param;

public interface TSequenceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SEQUENCE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	long countByExample(TSequenceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SEQUENCE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	int deleteByExample(TSequenceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SEQUENCE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	int deleteByPrimaryKey(String idName);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SEQUENCE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	int insert(TSequence record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SEQUENCE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	int insertSelective(TSequence record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SEQUENCE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	List<TSequence> selectByExample(TSequenceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SEQUENCE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	TSequence selectByPrimaryKey(String idName);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SEQUENCE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	int updateByExampleSelective(@Param("record") TSequence record, @Param("example") TSequenceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SEQUENCE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	int updateByExample(@Param("record") TSequence record, @Param("example") TSequenceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SEQUENCE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	int updateByPrimaryKeySelective(TSequence record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SEQUENCE
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	int updateByPrimaryKey(TSequence record);
}