package jp.co.fnj.storage.api.entity.mapper.generat;

import java.util.List;
import jp.co.fnj.storage.api.entity.model.generat.TSortOrder;
import jp.co.fnj.storage.api.entity.model.generat.TSortOrderExample;
import org.apache.ibatis.annotations.Param;

public interface TSortOrderMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SORT_ORDER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	long countByExample(TSortOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SORT_ORDER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	int deleteByExample(TSortOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SORT_ORDER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	int deleteByPrimaryKey(Integer sortOrderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SORT_ORDER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	int insert(TSortOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SORT_ORDER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	int insertSelective(TSortOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SORT_ORDER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	List<TSortOrder> selectByExample(TSortOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SORT_ORDER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	TSortOrder selectByPrimaryKey(Integer sortOrderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SORT_ORDER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	int updateByExampleSelective(@Param("record") TSortOrder record, @Param("example") TSortOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SORT_ORDER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	int updateByExample(@Param("record") TSortOrder record, @Param("example") TSortOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SORT_ORDER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	int updateByPrimaryKeySelective(TSortOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_SORT_ORDER
	 * @mbg.generated  Wed Nov 06 10:45:58 JST 2019
	 */
	int updateByPrimaryKey(TSortOrder record);
}