package jp.co.fnj.storage.api.entity.mapper.generat;

import java.util.List;
import jp.co.fnj.storage.api.entity.model.generat.TSortOrder;
import jp.co.fnj.storage.api.entity.model.generat.TSortOrderExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface TSortOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sort_order
     *
     * @mbg.generated
     */
    long countByExample(TSortOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sort_order
     *
     * @mbg.generated
     */
    int deleteByExample(TSortOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sort_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sortOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sort_order
     *
     * @mbg.generated
     */
    int insert(TSortOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sort_order
     *
     * @mbg.generated
     */
    int insertSelective(TSortOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sort_order
     *
     * @mbg.generated
     */
    List<TSortOrder> selectByExampleWithRowbounds(TSortOrderExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sort_order
     *
     * @mbg.generated
     */
    List<TSortOrder> selectByExample(TSortOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sort_order
     *
     * @mbg.generated
     */
    TSortOrder selectByPrimaryKey(String sortOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sort_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TSortOrder record, @Param("example") TSortOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sort_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TSortOrder record, @Param("example") TSortOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sort_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TSortOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sort_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSortOrder record);
}